---

GENERAL:
  interaction_mode: multi_agent
  agents: 2

  experience_logs:
    save: False
    load: False
    path: Logs/CamRest_MultiAgent_Train

  global_arguments:
    ontology: Domain/Domains/CamRestaurants-rules.json
    database: Domain/Domains/CamRestaurants-dbase.db
    domain: CamRest
    db_type: sql

DIALOGUE:
  num_dialogues: 1000
  domain: CamRest
  ontology_path: Domain/Domains/CamRestaurants-rules.json
  db_path: Domain/Domains/CamRestaurants-dbase.db
  db_type: sql


AGENT_0:
  role: system

  DM:
    policy:
      type: wolf_phc
  
      train: True
      learning_rate: 0.25
      exploration_rate: 0.995
      discount_factor: 0.8
      learning_decay_rate: 0.995
      exploration_decay_rate: 0.995

      policy_path: Models/Policies/Sys/wolf_phc_policy_sys.pkl

AGENT_1:
  role: user

  DM:
    policy:
      type: wolf_phc
  
      train: True
      learning_rate: 0.25
      exploration_rate: 0.995
      discount_factor: 0.8
      learning_decay_rate: 0.995
      exploration_decay_rate: 0.995

      policy_path: Models/Policies/User_0/wolf_phc_policy_usr.pkl
